# Generated by Django 6.0.4 on 2026-05-04 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0003_userprofile_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
