# Generated by Django 6.0.5 on 2026-06-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0006_routehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RouteHistory',
        ),
    ]
